[package]
name = "core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenvy = "0.15.6"
log = "0.4.17"
serde = "1.0.152"
serde_json = "1.0.91"
common = { path = "../common" }
