version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    restart: unless-stopped
volumes:
  db-data:
